[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string] $OutputPath,
  [string] $Version = "dev",
  [switch] $IncludeRuntime,
  [string] $RuntimePath
)

$ErrorActionPreference = "Stop"
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot ".." -Resolve)).Path
$workspaceRoot = (Resolve-Path (Join-Path $projectRoot "..\.." -Resolve)).Path
$destination = [IO.Path]::GetFullPath($OutputPath)
$stage = Join-Path ([IO.Path]::GetTempPath()) ("predixalearn-release-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $stage | Out-Null
try {
  # Only the local OCR application is included in the desktop release.
  $include = @("app", "web", "run.py", "requirements.txt", "constraints.txt", "package.json", "README.md", "scripts/libreoffice.lock.json", "scripts/launch_release.ps1")
  foreach ($entry in $include) {
    $source = Join-Path $projectRoot $entry
    if (Test-Path -LiteralPath $source) {
      $target = Join-Path $stage $entry
      New-Item -ItemType Directory -Force -Path (Split-Path $target) | Out-Null
      Copy-Item -LiteralPath $source -Destination $target -Recurse -Force
    }
  }
  # LibreOffice is a pinned local runtime outside the Python environment.  A
  # self-contained desktop bundle needs the validated installation, but not
  # the regenerable MSI download cache.
  $libreOfficeSource = Join-Path $workspaceRoot ".tools\libreoffice"
  if (Test-Path -LiteralPath $libreOfficeSource -PathType Container) {
    $toolsTarget = Join-Path $stage ".tools"
    New-Item -ItemType Directory -Force -Path $toolsTarget | Out-Null
    Copy-Item -LiteralPath $libreOfficeSource -Destination $toolsTarget -Recurse -Force
  }
  foreach ($entry in @("LICENSE", "NOTICE")) {
    $source = Join-Path $workspaceRoot $entry
    if (Test-Path -LiteralPath $source) {
      Copy-Item -LiteralPath $source -Destination (Join-Path $stage $entry) -Force
    }
  }
  if ($IncludeRuntime) {
    $runtimeSource = if ($RuntimePath) {
      [IO.Path]::GetFullPath($RuntimePath)
    } else {
      if ($env:PREDIXALEARN_VENV_DIR) {
        [IO.Path]::GetFullPath($env:PREDIXALEARN_VENV_DIR)
      } elseif (Test-Path -LiteralPath (Join-Path $projectRoot ".venv")) {
        Join-Path $projectRoot ".venv"
      } else {
        Join-Path $workspaceRoot ".venv"
      }
    }
    if (-not (Test-Path -LiteralPath $runtimeSource -PathType Container)) {
      throw "Runtime folder was not found: $runtimeSource"
    }
    $pythonCandidates = @(
      (Join-Path $runtimeSource "python.exe"),
      (Join-Path $runtimeSource "Scripts\python.exe")
    )
    if (-not ($pythonCandidates | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf })) {
      throw "Runtime folder must contain python.exe or Scripts\\python.exe: $runtimeSource"
    }
    Copy-Item -LiteralPath $runtimeSource -Destination (Join-Path $stage "runtime") -Recurse -Force
  }
  # Exclude generated bytecode and any legacy runtime records from the package.
  Get-ChildItem -LiteralPath $stage -Directory -Recurse -Force |
    Where-Object { $_.Name -in @("__pycache__", ".pytest_cache") } |
    Remove-Item -Recurse -Force
  $stagedLegacyHistory = Join-Path $stage "app\history"
  if (Test-Path -LiteralPath $stagedLegacyHistory) {
    Remove-Item -LiteralPath $stagedLegacyHistory -Recurse -Force
  }
  $manifest = [ordered]@{
    schema_version = 1
    version = $Version
    built_at = (Get-Date).ToUniversalTime().ToString("o")
    application = "PredixaLearn"
    data_root = "%LOCALAPPDATA%\PredixaLearn"
    runtime_included = [bool]$IncludeRuntime
  }
  $manifest | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $stage "release.json") -Encoding UTF8
  $parent = Split-Path $destination
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  if (Test-Path -LiteralPath $destination) { Remove-Item -LiteralPath $destination -Force }
  Compress-Archive -Path (Join-Path $stage "*") -DestinationPath $destination -CompressionLevel Optimal
  $hash = (Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash.ToLowerInvariant()
  Set-Content -LiteralPath ($destination + ".sha256") -Value ("$hash  " + (Split-Path $destination -Leaf)) -Encoding ASCII
  Write-Output "Created $destination"
}
finally {
  if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
}
