apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector: {matchLabels: {app: {{ .Release.Name }}}}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{namespaceSelector: {}}]
      ports: [{protocol: TCP, port: 8100}]
  egress:
    - to: [{namespaceSelector: {}}]
    - to: [{ipBlock: {cidr: 0.0.0.0/0, except: ["169.254.0.0/16"]}}]
      ports: [{protocol: TCP, port: 443}]
